baseURL = 'https://raciod.com/'
theme = 'terminal'

[params]
  themeColor = 'green' 

# ==========================================
# ENGLISH CONFIGURATION (Default)
# ==========================================
[languages.en]
  languageCode = 'en-us'
  languageName = 'English'
  weight = 1
  title = 'raciod@portfolio'

  [languages.en.params]
    logoText = 'raciod@192:~$'
    description = 'Personal developer portfolio.'

  [[languages.en.menu.main]]
    name = 'About'
    url = '/about/'
    weight = 1
  [[languages.en.menu.main]]
    name = 'Projects'
    url = '/projects/'
    weight = 2

# ==========================================
# FRENCH CONFIGURATION
# ==========================================
[languages.fr]
  languageCode = 'fr-fr'
  languageName = 'Français'
  weight = 2
  title = 'raciod@portfolio [FR]'

  [languages.fr.params]
    logoText = 'raciod@192:~$'
    description = 'Portfolio de développement personnel.'

  [[languages.fr.menu.main]]
    name = 'À Propos'
    url = '/about/'
    weight = 1
  [[languages.fr.menu.main]]
    name = 'Projets'
    url = '/projects/'
    weight = 2
