baseURL = 'http://raciod.com/'
locale = 'en-us'
title = 'My Portfolio'
theme = 'hugo-theme-shell'

[Params]
  description = "raciod's Portfolio"

[Params.Terminal]
  scheme = "monokai"
  userName = "raciod"
  pcName = "84"
  workDir = "myspace"
  profile = "profile.txt"
  
  description = """
Hi, welcome to my space! I am a student.
I love computers, trying new things, Linux, security, and programming.
This is my space to share what I care about.
  """
  
  # Main Terminal Speeds
  ps1Delay = 20
  commandDelay = 50
  stdoutDelay = 10

  # Subpage Speeds (Prepped for Vim later)
  titleDelay = 20
  contentDelay = 10

[Params.Tree]
  use = true
  folderName = "my_activity"
  files = [
    ["links", "/links/"],
    ["projects", "/projects/"]
  ]
